-- ============================================================
-- BranchMaster: Add Indian Compliance Columns
-- ============================================================

USE [obms];
GO

PRINT '=== Altering BranchMaster for Indian Fields ==='

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='BranchMaster' AND COLUMN_NAME='GSTIN')
    ALTER TABLE BranchMaster ADD GSTIN NVARCHAR(15) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='BranchMaster' AND COLUMN_NAME='PANNumber')
    ALTER TABLE BranchMaster ADD PANNumber NVARCHAR(10) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='BranchMaster' AND COLUMN_NAME='TANNumber')
    ALTER TABLE BranchMaster ADD TANNumber NVARCHAR(10) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='BranchMaster' AND COLUMN_NAME='IndianState')
    ALTER TABLE BranchMaster ADD IndianState NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='BranchMaster' AND COLUMN_NAME='GSTRegistrationStatus')
    ALTER TABLE BranchMaster ADD GSTRegistrationStatus NVARCHAR(20) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='BranchMaster' AND COLUMN_NAME='IsGSTCompliant')
    ALTER TABLE BranchMaster ADD IsGSTCompliant BIT NOT NULL DEFAULT 0;

-- Also check Employee table for any missing columns
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employee' AND COLUMN_NAME='Aadhaar')
    ALTER TABLE Employee ADD Aadhaar NVARCHAR(12) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employee' AND COLUMN_NAME='PAN')
    ALTER TABLE Employee ADD PAN NVARCHAR(10) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employee' AND COLUMN_NAME='PF_AccountNumber')
    ALTER TABLE Employee ADD PF_AccountNumber NVARCHAR(26) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employee' AND COLUMN_NAME='ESI_Number')
    ALTER TABLE Employee ADD ESI_Number NVARCHAR(17) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employee' AND COLUMN_NAME='IFSC_Code')
    ALTER TABLE Employee ADD IFSC_Code NVARCHAR(11) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employee' AND COLUMN_NAME='BankAccountNumber')
    ALTER TABLE Employee ADD BankAccountNumber NVARCHAR(34) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employee' AND COLUMN_NAME='BankName')
    ALTER TABLE Employee ADD BankName NVARCHAR(100) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employee' AND COLUMN_NAME='BankBranch')
    ALTER TABLE Employee ADD BankBranch NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employee' AND COLUMN_NAME='UAN_Number')
    ALTER TABLE Employee ADD UAN_Number NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employee' AND COLUMN_NAME='IndianState')
    ALTER TABLE Employee ADD IndianState NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employee' AND COLUMN_NAME='SalaryGroup')
    ALTER TABLE Employee ADD SalaryGroup NVARCHAR(20) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employee' AND COLUMN_NAME='UPIId')
    ALTER TABLE Employee ADD UPIId NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employee' AND COLUMN_NAME='ProfessionalTax_State')
    ALTER TABLE Employee ADD ProfessionalTax_State NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Employee' AND COLUMN_NAME='EMP_BASIC_RATE')
    ALTER TABLE Employee ADD EMP_BASIC_RATE DECIMAL(18,2) NOT NULL DEFAULT 0;

-- Attendance table
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Attendance' AND COLUMN_NAME='AttendanceDate')
    ALTER TABLE Attendance ADD AttendanceDate DATE NOT NULL DEFAULT GETDATE();

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Attendance' AND COLUMN_NAME='TimeStart')
    ALTER TABLE Attendance ADD TimeStart TIME NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Attendance' AND COLUMN_NAME='TimeEnd')
    ALTER TABLE Attendance ADD TimeEnd TIME NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Attendance' AND COLUMN_NAME='Status')
    ALTER TABLE Attendance ADD Status NVARCHAR(20) NULL;

-- ClientMaster compliance fields
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='GSTIN')
    ALTER TABLE ClientMaster ADD GSTIN NVARCHAR(20) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='PANNumber')
    ALTER TABLE ClientMaster ADD PANNumber NVARCHAR(10) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='TANNumber')
    ALTER TABLE ClientMaster ADD TANNumber NVARCHAR(10) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='CINNumber')
    ALTER TABLE ClientMaster ADD CINNumber NVARCHAR(21) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='GSTRegistrationStatus')
    ALTER TABLE ClientMaster ADD GSTRegistrationStatus NVARCHAR(20) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='IndianState')
    ALTER TABLE ClientMaster ADD IndianState NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='PINCode')
    ALTER TABLE ClientMaster ADD PINCode NVARCHAR(6) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='IsGSTCompliant')
    ALTER TABLE ClientMaster ADD IsGSTCompliant BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='IsPANCompliant')
    ALTER TABLE ClientMaster ADD IsPANCompliant BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='IsTANCompliant')
    ALTER TABLE ClientMaster ADD IsTANCompliant BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='IsCINCompliant')
    ALTER TABLE ClientMaster ADD IsCINCompliant BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='ComplianceCheckDate')
    ALTER TABLE ClientMaster ADD ComplianceCheckDate DATE NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='ComplianceRemarks')
    ALTER TABLE ClientMaster ADD ComplianceRemarks NVARCHAR(500) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='ShippingAddress1')
    ALTER TABLE ClientMaster ADD ShippingAddress1 NVARCHAR(200) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='ShippingAddress2')
    ALTER TABLE ClientMaster ADD ShippingAddress2 NVARCHAR(200) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='ShippingCity')
    ALTER TABLE ClientMaster ADD ShippingCity NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='ShippingState')
    ALTER TABLE ClientMaster ADD ShippingState NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='ShippingPINCode')
    ALTER TABLE ClientMaster ADD ShippingPINCode NVARCHAR(6) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='BillingAddress1')
    ALTER TABLE ClientMaster ADD BillingAddress1 NVARCHAR(200) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='BillingAddress2')
    ALTER TABLE ClientMaster ADD BillingAddress2 NVARCHAR(200) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='BillingCity')
    ALTER TABLE ClientMaster ADD BillingCity NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='BillingState')
    ALTER TABLE ClientMaster ADD BillingState NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ClientMaster' AND COLUMN_NAME='BillingPINCode')
    ALTER TABLE ClientMaster ADD BillingPINCode NVARCHAR(6) NULL;

-- PFConfiguration table
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PFConfiguration' AND COLUMN_NAME='Financial_Year')
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='PFConfiguration')
    BEGIN
        CREATE TABLE PFConfiguration (
            Id INT IDENTITY(1,1) PRIMARY KEY,
            Employee_Rate DECIMAL(5,2) NOT NULL DEFAULT 12.00,
            Employer_Rate DECIMAL(5,2) NOT NULL DEFAULT 12.00,
            Employer_EPS_Rate DECIMAL(5,2) NOT NULL DEFAULT 8.33,
            Basic_Salary_Limit DECIMAL(10,2) NOT NULL DEFAULT 15000.00,
            Effective_Date DATE NOT NULL DEFAULT GETDATE(),
            Is_Active BIT NOT NULL DEFAULT 1,
            Created_Date DATE NOT NULL DEFAULT GETDATE(),
            Financial_Year NVARCHAR(9) NOT NULL DEFAULT '2024-2025'
        );
    END
END

-- ESIConfiguration table
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='ESIConfiguration')
BEGIN
    CREATE TABLE ESIConfiguration (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        Employee_Rate DECIMAL(5,2) NOT NULL DEFAULT 0.75,
        Employer_Rate DECIMAL(5,2) NOT NULL DEFAULT 3.25,
        Basic_Salary_Limit DECIMAL(10,2) NOT NULL DEFAULT 21000.00,
        Effective_Date DATE NOT NULL DEFAULT GETDATE(),
        Is_Active BIT NOT NULL DEFAULT 1,
        Created_Date DATE NOT NULL DEFAULT GETDATE(),
        Financial_Year NVARCHAR(9) NOT NULL DEFAULT '2024-2025'
    );
END

-- ProfessionalTaxConfiguration table
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='ProfessionalTaxConfiguration')
BEGIN
    CREATE TABLE ProfessionalTaxConfiguration (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        State NVARCHAR(50) NOT NULL,
        MinSalary DECIMAL(10,2) NOT NULL,
        MaxSalary DECIMAL(10,2) NULL,
        TaxAmount DECIMAL(10,2) NOT NULL,
        EffectiveDate DATE NOT NULL DEFAULT GETDATE(),
        IsActive BIT NOT NULL DEFAULT 1,
        CreatedDate DATE NOT NULL DEFAULT GETDATE(),
        CreatedBy NVARCHAR(50) NOT NULL DEFAULT 'system',
        LastUpdatedDate DATE NULL,
        LastUpdatedBy NVARCHAR(50) NULL
    );
END

-- TDSSlabConfiguration table  
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='TDSSlabConfiguration')
BEGIN
    CREATE TABLE TDSSlabConfiguration (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        MinIncome DECIMAL(18,2) NOT NULL,
        MaxIncome DECIMAL(18,2) NULL,
        TaxRate DECIMAL(5,2) NOT NULL,
        SurchargeRate DECIMAL(5,2) NOT NULL DEFAULT 0,
        HealthEducationCess DECIMAL(5,2) NOT NULL DEFAULT 4.00,
        FinancialYear NVARCHAR(9) NOT NULL,
        TaxRegime NVARCHAR(10) NOT NULL DEFAULT 'New',
        IsActive BIT NOT NULL DEFAULT 1,
        CreatedDate DATE NOT NULL DEFAULT GETDATE(),
        CreatedBy NVARCHAR(50) NOT NULL DEFAULT 'system'
    );
END

PRINT '=== Schema Alteration Complete ==='

-- Verify new columns
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('BranchMaster','ClientMaster','Employee','Attendance')
  AND COLUMN_NAME IN ('GSTIN','PANNumber','TANNumber','IndianState','IsGSTCompliant',
                      'AadhaarNumber','Aadhaar','PAN','IFSC_Code','UAN_Number',
                      'AttendanceDate','Status','ComplianceCheckDate','ComplianceRemarks')
ORDER BY TABLE_NAME, COLUMN_NAME;
